<!--#include file="Connections/database.asp" -->
<%
if session("wgsANM_usr")="" then
    Response.Redirect "Logout.asp"
End if
clienteid = request("clienid")
eventoid = request("evenid")
    Set conn = Server.CreateObject("ADODB.Connection")
    Conn.Open(MM_WGS_STRING)
sql = "SELECT Clientes.ID_Clientes, Clientes.Cli_Numero, Clientes.Cli_Apellido, Clientes.Cli_Nombre, Clientes.Cli_TipoDNI, Clientes.Cli_DNInro, Clientes.Cli_Nacimiento, Clientes.Cli_Genero, Clientes.Cli_Email, Status.Sta_Nombre, Empresas.Emp_Corto, Clientes.Cli_Contacto, Clientes.Cli_Fechaultimo, Clientes.Cli_Fechaprox, Clientes.Cli_Comentario, Clientes.Cli_Telefono2, Clientes.Cli_CPNuevo, Clientes.Cli_Eventos, Clientes.Cli_Valor, Clientes.Cli_Usuario, Usuarios.Usr_Apellidos, Usuarios.Usr_Nombres, Localidades.Loc_Localidad, Localidades.Loc_Provincia, Localidades.Loc_CP, Localidades.Loc_CPAprov, Clientes.Cli_Inicio, Clientes.Cli_Calle, Clientes.Cli_CalleNro, Clientes.Cli_Piso, Clientes.Cli_Depto, Clientes.Cli_Ampli, Clientes.Cli_Inicio, Clientes.Cli_Status FROM Localidades INNER JOIN ((Empresas INNER JOIN (Status INNER JOIN Clientes ON Status.ID_Status = Clientes.Cli_Status) ON Empresas.ID_Empresas = Clientes.Cli_Empresa) INNER JOIN Usuarios ON Clientes.Cli_Usuario = Usuarios.ID_Usuarios) ON Localidades.Id_Localidad = Clientes.Cli_Localidad WHERE (((Clientes.Cli_Numero)="& clienteid & "))"
    Set rs = Server.CreateObject("ADODB.Recordset")
    rs.Open sql, conn, adOpenStatic, adLockReadOnly
	
Set Mail = Server.CreateObject ("CDO.Message")
Mail.From = Remitente
Mail.To = Receptor
Mail.Subject = "Solicitud [" & clienteid & "]"
HTML = "<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4.01//EN"" ""http://www.w3.org/TR/html4/strict.dtd"">" & NL
HTML = HTML & "<html>" 
HTML = HTML & "<head>" 
HTML = HTML & "<meta http-equiv=""Content-Type"" content=""text/html; charset=utf-8"">" 
HTML = HTML & "<title>Documento sin t&iacute;tulo</title>" 
HTML = HTML & "<style type=""text/css"">" 
HTML = HTML & "<!--" 
HTML = HTML & ".Estilo1 {font-family: ""Trebuchet MS"", Tahoma, Verdana, Arial}" 
HTML = HTML & ".Estilo2 {" 
HTML = HTML & "	font-size: small;" 
HTML = HTML & "	font-weight: bold;"
HTML = HTML & "}"
HTML = HTML & "-->" 
HTML = HTML & "</style>" 
HTML = HTML & "</head>"
HTML = HTML & "<body>"
HTML = HTML & "<table width=""800"" border=""1"" cellpadding=""0"" cellspacing=""0"" bordercolor=""#999999"" class=""Estilo1"">"
HTML = HTML & "<tr bgcolor=""#CCCCCC"">"
HTML = HTML & "<th colspan=""4"" scope=""col"">Cliente: [Apellido], [Nombre]  </th>"
HTML = HTML & " </tr>" 
HTML = HTML & "<tr>" 
HTML = HTML & "<td colspan=""4""><div align=""center"">Empresa:[Empresa]</div></td>" 
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td>Linea:</td>"
HTML = HTML & "<td>[Nro de Telefono] </td>"
HTML = HTML & "<td>G&eacute;nero</td>"
HTML = HTML & "<td><p>[Genero] </p>    </td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td>Documento:</td>"
HTML = HTML & "<td>[TipoDNI][NroDNI]</td>"
HTML = HTML & "<td>Nacimiento</td>"
HTML = HTML & "<td>[Fecha Nacimiento]]</td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr bgcolor=""#CCCCCC"">"
HTML = HTML & "<td colspan=""4""><div align=""center""><strong>Domicilio</strong></div></td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td>Calle:</td>"
HTML = HTML & "<td>[Calle]</td>"
HTML = HTML & "<td>Nro:</td>"
HTML = HTML & "<td>[CalleNro]</td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td>Piso:</td>"
HTML = HTML & "<td>[Piso]</td>"
HTML = HTML & "<td>Depto.:</td>"
HTML = HTML & "<td>[Dpto]</td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td colspan=""4"">Ampliaci&oacute;n: [Ampliacion] </td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td>Localidad:</td>"
HTML = HTML & "<td>[Localidad],[Provincia]</td>"
HTML = HTML & "<td>C&oacute;digo Postal:</td>"
HTML = HTML & "<td>[CPA]</td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr bgcolor=""#CCCCCC"">"
HTML = HTML & "<td colspan=""4""><div align=""center""><strong>Datos de Contacto </strong></div>"
HTML = HTML & "</td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td colspan=""4""><div align=""center"">Persona a Contactar: [Persona Contacto] </div></td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td colspan=""4""><div align=""center"">Correo Electronico: [email]</div></td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td colspan=""4""><div align=""center"">Telefono Fijo: [Telefono Fijo] </div></td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td colspan=""4""><div align=""center"">Observaciones</div></td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td colspan=""4""><div align=""center"">[Observaciones]</div></td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td colspan=""4"" bgcolor=""#CCCCCC""><div align=""center""><strong>Datos de la Cita </strong></div></td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td>Plan Ofrecido:</td>"
HTML = HTML & "<td>[Plan]</td>"
HTML = HTML & "<td>Dia y Hora:</td>"
HTML = HTML & "<td>[Fechaprox]</td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td>Aparato Ofrecido: </td>"
HTML = HTML & "<td>[Marca]</td>"
HTML = HTML & "<td>Modelo:</td>"
HTML = HTML & "<td>[Modelo]</td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td colspan=""4""><div align=""center"">Nota</div></td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td colspan=""4""><div align=""center"">[Nota]</div></td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td>Asesor:</td>"
HTML = HTML & "<td>[UserApellido],[UserNombre]</td>"
HTML = HTML & "<td>Realizado:</td>"
HTML = HTML & "<td>[Now]</td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td>Id Cliente: </td>"
HTML = HTML & "<td>[Id_Cliente]</td>"
HTML = HTML & "<td>Evento:</td>"
HTML = HTML & "<td>[Id_Evento]</td>"
HTML = HTML & "</tr>"
HTML = HTML & "<tr>"
HTML = HTML & "<td colspan=""4"" bgcolor=""#CCCCCC""><div align=""center"" class=""Estilo2"">WG Sistemas </div></td>"
HTML = HTML & "</tr>"
HTML = HTML & "</table>"
HTML = HTML & "</body>"
HTML = HTML & "</html>"
Mail.HTMLBody = HTML
Mail.Send
Set Mail = Nothing
Response.Write("Envio exitoso")
%>